name: TT_Auto_Build

on:
  push:
    tags:
      - "*"

jobs:
  Linux_x86-64_musl:
    name: for Linux_x86-64
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install musl-tools
        run: sudo apt-get update --allow-unauthenticated -qq && sudo apt-get install -y musl-tools
      - name: Rustup
        run: rustup target add x86_64-unknown-linux-musl
      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-musl
      - name: Strip
        run: strip target/x86_64-unknown-linux-musl/release/tt
      - name: Move
        run: mv target/x86_64-unknown-linux-musl/release/tt tt_x86_64-unknown-linux-musl
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: tt_x86_64-unknown-linux-musl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Linux_aarch64_musl:
    name: for Linux_aarch64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install gcc-aarch64-linux-gnu
        run: sudo apt-get update --allow-unauthenticated -qq && sudo apt-get install -y gcc-aarch64-linux-gnu
      - name: Ruspup
        run: rustup target add aarch64-unknown-linux-musl
      - name: Build
        run: CC=aarch64-linux-gnu-gcc CFLAGS=-D_FORTIFY_SOURCE=1 cargo build --release --target aarch64-unknown-linux-musl
      - name: Strip
        run: aarch64-linux-gnu-strip target/aarch64-unknown-linux-musl/release/tt
      - name: Move
        run: mv target/aarch64-unknown-linux-musl/release/tt tt_aarch64-unknown-linux-musl
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: tt_aarch64-unknown-linux-musl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
